[project]
name = "nstow"
version = "0.21.0"
description = "GNU Stow Reimplementation by Nozomi Miyamori"
readme = "README.md"
requires-python = ">=3.12"
license = {file = "COPYING"}
authors = [
    {email = "inspc43313@yahoo.co.jp"},
    {name = "Nozomi Miyamori"},
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Console",
    "Topic :: System :: Filesystems",
    "Programming Language :: Python :: 3.12",
]
[project.urls]
repository = "https://github.com/nm004/nstow"

[project.scripts]
nstow = "nstow:__main__.main"
